# Generated by Django 4.1 on 2023-10-17 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0002_cart_coffee_cartitem_cart_items_cart_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="order",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("total", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="index.cart"
                    ),
                ),
            ],
        ),
    ]
