# Generated by Django 4.1 on 2023-10-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0003_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
